modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
logoFile = "expandedae.png"
mixins = ["expandedae.mixins.json"]

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependency."${mod_id}"]]
modId = "ae2"
mandatory = true
ordering = "AFTER"
side = "BOTH"

[[dependency."${mod_id}"]]
modId = "expatternprovider"
mandatory = true
ordering = "AFTER"
side = "BOTH"

[[dependency."${mod_id}"]]
modId = "megacells"
mandatory = false
ordering = "AFTER"
side = "BOTH"

[[dependency."${mod_id}"]]
modId = "ae2wtlib"
mandatory = true
ordering = "AFTER"
side = "BOTH"

[[dependency."${mod_id}"]]
modId = "architectury"
mandatory = false
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "curios"
mandatory = false
versionRange = "[5.0.0,)"
ordering = "AFTER"
side = "BOTH"