name: Publish

on:
  push:
    tags:
      - '(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write # needed to create GitHub releases

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build Project
        run: ./gradlew build --warning-mode all --build-cache

      - name: Publish to Maven
        env:
          MAVEN_USER: "${{ secrets.MAVEN_USER }}"
          MAVEN_PASSWORD: "${{ secrets.MAVEN_PASSWORD }}"
        run: ./gradlew publish

      - name: Publish to GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: "jar/*.jar" # todo change when this is moved to ModDevGradle
          generate_release_notes: true
          fail_on_unmatched_files: true
